name: Docker Qt5 Image CI

on: [push]

jobs:

  build:

    runs-on: arlanov/debian_stretch_slim_qt5:latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
